/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VpnRouteImport } from './routes/vpn'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TestRouteImport } from './routes/test'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SpoofTimezoneRouteImport } from './routes/spoof-timezone'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FrRouteImport } from './routes/fr'
import { Route as EngineLevelSpoofingRouteImport } from './routes/engine-level-spoofing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpoofLocationIndexRouteImport } from './routes/spoof-location.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SpoofLocationSafariRouteImport } from './routes/spoof-location.safari'
import { Route as SpoofLocationFirefoxRouteImport } from './routes/spoof-location.firefox'
import { Route as SpoofLocationEdgeRouteImport } from './routes/spoof-location.edge'
import { Route as SpoofLocationChromeRouteImport } from './routes/spoof-location.chrome'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const VpnRoute = VpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofTimezoneRoute = SpoofTimezoneRouteImport.update({
  id: '/spoof-timezone',
  path: '/spoof-timezone',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineLevelSpoofingRoute = EngineLevelSpoofingRouteImport.update({
  id: '/engine-level-spoofing',
  path: '/engine-level-spoofing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofLocationIndexRoute = SpoofLocationIndexRouteImport.update({
  id: '/spoof-location/',
  path: '/spoof-location/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofLocationSafariRoute = SpoofLocationSafariRouteImport.update({
  id: '/spoof-location/safari',
  path: '/spoof-location/safari',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofLocationFirefoxRoute = SpoofLocationFirefoxRouteImport.update({
  id: '/spoof-location/firefox',
  path: '/spoof-location/firefox',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofLocationEdgeRoute = SpoofLocationEdgeRouteImport.update({
  id: '/spoof-location/edge',
  path: '/spoof-location/edge',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofLocationChromeRoute = SpoofLocationChromeRouteImport.update({
  id: '/spoof-location/chrome',
  path: '/spoof-location/chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/engine-level-spoofing': typeof EngineLevelSpoofingRoute
  '/fr': typeof FrRoute
  '/privacy': typeof PrivacyRoute
  '/spoof-timezone': typeof SpoofTimezoneRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/vpn': typeof VpnRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/spoof-location/chrome': typeof SpoofLocationChromeRoute
  '/spoof-location/edge': typeof SpoofLocationEdgeRoute
  '/spoof-location/firefox': typeof SpoofLocationFirefoxRoute
  '/spoof-location/safari': typeof SpoofLocationSafariRoute
  '/blog/': typeof BlogIndexRoute
  '/spoof-location/': typeof SpoofLocationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/engine-level-spoofing': typeof EngineLevelSpoofingRoute
  '/fr': typeof FrRoute
  '/privacy': typeof PrivacyRoute
  '/spoof-timezone': typeof SpoofTimezoneRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/vpn': typeof VpnRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/spoof-location/chrome': typeof SpoofLocationChromeRoute
  '/spoof-location/edge': typeof SpoofLocationEdgeRoute
  '/spoof-location/firefox': typeof SpoofLocationFirefoxRoute
  '/spoof-location/safari': typeof SpoofLocationSafariRoute
  '/blog': typeof BlogIndexRoute
  '/spoof-location': typeof SpoofLocationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/engine-level-spoofing': typeof EngineLevelSpoofingRoute
  '/fr': typeof FrRoute
  '/privacy': typeof PrivacyRoute
  '/spoof-timezone': typeof SpoofTimezoneRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/vpn': typeof VpnRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/spoof-location/chrome': typeof SpoofLocationChromeRoute
  '/spoof-location/edge': typeof SpoofLocationEdgeRoute
  '/spoof-location/firefox': typeof SpoofLocationFirefoxRoute
  '/spoof-location/safari': typeof SpoofLocationSafariRoute
  '/blog/': typeof BlogIndexRoute
  '/spoof-location/': typeof SpoofLocationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/engine-level-spoofing'
    | '/fr'
    | '/privacy'
    | '/spoof-timezone'
    | '/support'
    | '/terms'
    | '/test'
    | '/verify'
    | '/vpn'
    | '/blog/$slug'
    | '/spoof-location/chrome'
    | '/spoof-location/edge'
    | '/spoof-location/firefox'
    | '/spoof-location/safari'
    | '/blog/'
    | '/spoof-location/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/engine-level-spoofing'
    | '/fr'
    | '/privacy'
    | '/spoof-timezone'
    | '/support'
    | '/terms'
    | '/test'
    | '/verify'
    | '/vpn'
    | '/blog/$slug'
    | '/spoof-location/chrome'
    | '/spoof-location/edge'
    | '/spoof-location/firefox'
    | '/spoof-location/safari'
    | '/blog'
    | '/spoof-location'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/engine-level-spoofing'
    | '/fr'
    | '/privacy'
    | '/spoof-timezone'
    | '/support'
    | '/terms'
    | '/test'
    | '/verify'
    | '/vpn'
    | '/blog/$slug'
    | '/spoof-location/chrome'
    | '/spoof-location/edge'
    | '/spoof-location/firefox'
    | '/spoof-location/safari'
    | '/blog/'
    | '/spoof-location/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EngineLevelSpoofingRoute: typeof EngineLevelSpoofingRoute
  FrRoute: typeof FrRoute
  PrivacyRoute: typeof PrivacyRoute
  SpoofTimezoneRoute: typeof SpoofTimezoneRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TestRoute: typeof TestRoute
  VerifyRoute: typeof VerifyRoute
  VpnRoute: typeof VpnRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SpoofLocationChromeRoute: typeof SpoofLocationChromeRoute
  SpoofLocationEdgeRoute: typeof SpoofLocationEdgeRoute
  SpoofLocationFirefoxRoute: typeof SpoofLocationFirefoxRoute
  SpoofLocationSafariRoute: typeof SpoofLocationSafariRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SpoofLocationIndexRoute: typeof SpoofLocationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vpn': {
      id: '/vpn'
      path: '/vpn'
      fullPath: '/vpn'
      preLoaderRoute: typeof VpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-timezone': {
      id: '/spoof-timezone'
      path: '/spoof-timezone'
      fullPath: '/spoof-timezone'
      preLoaderRoute: typeof SpoofTimezoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine-level-spoofing': {
      id: '/engine-level-spoofing'
      path: '/engine-level-spoofing'
      fullPath: '/engine-level-spoofing'
      preLoaderRoute: typeof EngineLevelSpoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-location/': {
      id: '/spoof-location/'
      path: '/spoof-location'
      fullPath: '/spoof-location/'
      preLoaderRoute: typeof SpoofLocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-location/safari': {
      id: '/spoof-location/safari'
      path: '/spoof-location/safari'
      fullPath: '/spoof-location/safari'
      preLoaderRoute: typeof SpoofLocationSafariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-location/firefox': {
      id: '/spoof-location/firefox'
      path: '/spoof-location/firefox'
      fullPath: '/spoof-location/firefox'
      preLoaderRoute: typeof SpoofLocationFirefoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-location/edge': {
      id: '/spoof-location/edge'
      path: '/spoof-location/edge'
      fullPath: '/spoof-location/edge'
      preLoaderRoute: typeof SpoofLocationEdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-location/chrome': {
      id: '/spoof-location/chrome'
      path: '/spoof-location/chrome'
      fullPath: '/spoof-location/chrome'
      preLoaderRoute: typeof SpoofLocationChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EngineLevelSpoofingRoute: EngineLevelSpoofingRoute,
  FrRoute: FrRoute,
  PrivacyRoute: PrivacyRoute,
  SpoofTimezoneRoute: SpoofTimezoneRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TestRoute: TestRoute,
  VerifyRoute: VerifyRoute,
  VpnRoute: VpnRoute,
  BlogSlugRoute: BlogSlugRoute,
  SpoofLocationChromeRoute: SpoofLocationChromeRoute,
  SpoofLocationEdgeRoute: SpoofLocationEdgeRoute,
  SpoofLocationFirefoxRoute: SpoofLocationFirefoxRoute,
  SpoofLocationSafariRoute: SpoofLocationSafariRoute,
  BlogIndexRoute: BlogIndexRoute,
  SpoofLocationIndexRoute: SpoofLocationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
