/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VpnRouteImport } from './routes/vpn'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TestRouteImport } from './routes/test'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SpoofTimezoneRouteImport } from './routes/spoof-timezone'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FrRouteImport } from './routes/fr'
import { Route as EngineLevelSpoofingRouteImport } from './routes/engine-level-spoofing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpoofLocationIndexRouteImport } from './routes/spoof-location.index'
import { Route as FrIndexRouteImport } from './routes/fr.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SpoofLocationSafariRouteImport } from './routes/spoof-location.safari'
import { Route as SpoofLocationFirefoxRouteImport } from './routes/spoof-location.firefox'
import { Route as SpoofLocationEdgeRouteImport } from './routes/spoof-location.edge'
import { Route as SpoofLocationChromeRouteImport } from './routes/spoof-location.chrome'
import { Route as FrVpnRouteImport } from './routes/fr.vpn'
import { Route as FrVerifyRouteImport } from './routes/fr.verify'
import { Route as FrTermsRouteImport } from './routes/fr.terms'
import { Route as FrSupportRouteImport } from './routes/fr.support'
import { Route as FrSpoofTimezoneRouteImport } from './routes/fr.spoof-timezone'
import { Route as FrPrivacyRouteImport } from './routes/fr.privacy'
import { Route as FrEngineLevelSpoofingRouteImport } from './routes/fr.engine-level-spoofing'
import { Route as FrAboutRouteImport } from './routes/fr.about'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as FrSpoofLocationIndexRouteImport } from './routes/fr.spoof-location.index'
import { Route as FrBlogIndexRouteImport } from './routes/fr.blog.index'
import { Route as FrSpoofLocationSafariRouteImport } from './routes/fr.spoof-location.safari'
import { Route as FrSpoofLocationFirefoxRouteImport } from './routes/fr.spoof-location.firefox'
import { Route as FrSpoofLocationEdgeRouteImport } from './routes/fr.spoof-location.edge'
import { Route as FrSpoofLocationChromeRouteImport } from './routes/fr.spoof-location.chrome'
import { Route as FrBlogSlugRouteImport } from './routes/fr.blog.$slug'

const VpnRoute = VpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofTimezoneRoute = SpoofTimezoneRouteImport.update({
  id: '/spoof-timezone',
  path: '/spoof-timezone',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineLevelSpoofingRoute = EngineLevelSpoofingRouteImport.update({
  id: '/engine-level-spoofing',
  path: '/engine-level-spoofing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofLocationIndexRoute = SpoofLocationIndexRouteImport.update({
  id: '/spoof-location/',
  path: '/spoof-location/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofLocationSafariRoute = SpoofLocationSafariRouteImport.update({
  id: '/spoof-location/safari',
  path: '/spoof-location/safari',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofLocationFirefoxRoute = SpoofLocationFirefoxRouteImport.update({
  id: '/spoof-location/firefox',
  path: '/spoof-location/firefox',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofLocationEdgeRoute = SpoofLocationEdgeRouteImport.update({
  id: '/spoof-location/edge',
  path: '/spoof-location/edge',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofLocationChromeRoute = SpoofLocationChromeRouteImport.update({
  id: '/spoof-location/chrome',
  path: '/spoof-location/chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const FrVpnRoute = FrVpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => FrRoute,
} as any)
const FrVerifyRoute = FrVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => FrRoute,
} as any)
const FrTermsRoute = FrTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => FrRoute,
} as any)
const FrSupportRoute = FrSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => FrRoute,
} as any)
const FrSpoofTimezoneRoute = FrSpoofTimezoneRouteImport.update({
  id: '/spoof-timezone',
  path: '/spoof-timezone',
  getParentRoute: () => FrRoute,
} as any)
const FrPrivacyRoute = FrPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => FrRoute,
} as any)
const FrEngineLevelSpoofingRoute = FrEngineLevelSpoofingRouteImport.update({
  id: '/engine-level-spoofing',
  path: '/engine-level-spoofing',
  getParentRoute: () => FrRoute,
} as any)
const FrAboutRoute = FrAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => FrRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrSpoofLocationIndexRoute = FrSpoofLocationIndexRouteImport.update({
  id: '/spoof-location/',
  path: '/spoof-location/',
  getParentRoute: () => FrRoute,
} as any)
const FrBlogIndexRoute = FrBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => FrRoute,
} as any)
const FrSpoofLocationSafariRoute = FrSpoofLocationSafariRouteImport.update({
  id: '/spoof-location/safari',
  path: '/spoof-location/safari',
  getParentRoute: () => FrRoute,
} as any)
const FrSpoofLocationFirefoxRoute = FrSpoofLocationFirefoxRouteImport.update({
  id: '/spoof-location/firefox',
  path: '/spoof-location/firefox',
  getParentRoute: () => FrRoute,
} as any)
const FrSpoofLocationEdgeRoute = FrSpoofLocationEdgeRouteImport.update({
  id: '/spoof-location/edge',
  path: '/spoof-location/edge',
  getParentRoute: () => FrRoute,
} as any)
const FrSpoofLocationChromeRoute = FrSpoofLocationChromeRouteImport.update({
  id: '/spoof-location/chrome',
  path: '/spoof-location/chrome',
  getParentRoute: () => FrRoute,
} as any)
const FrBlogSlugRoute = FrBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => FrRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/engine-level-spoofing': typeof EngineLevelSpoofingRoute
  '/fr': typeof FrRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/spoof-timezone': typeof SpoofTimezoneRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/vpn': typeof VpnRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/engine-level-spoofing': typeof FrEngineLevelSpoofingRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/spoof-timezone': typeof FrSpoofTimezoneRoute
  '/fr/support': typeof FrSupportRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr/verify': typeof FrVerifyRoute
  '/fr/vpn': typeof FrVpnRoute
  '/spoof-location/chrome': typeof SpoofLocationChromeRoute
  '/spoof-location/edge': typeof SpoofLocationEdgeRoute
  '/spoof-location/firefox': typeof SpoofLocationFirefoxRoute
  '/spoof-location/safari': typeof SpoofLocationSafariRoute
  '/blog/': typeof BlogIndexRoute
  '/fr/': typeof FrIndexRoute
  '/spoof-location/': typeof SpoofLocationIndexRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/fr/spoof-location/chrome': typeof FrSpoofLocationChromeRoute
  '/fr/spoof-location/edge': typeof FrSpoofLocationEdgeRoute
  '/fr/spoof-location/firefox': typeof FrSpoofLocationFirefoxRoute
  '/fr/spoof-location/safari': typeof FrSpoofLocationSafariRoute
  '/fr/blog/': typeof FrBlogIndexRoute
  '/fr/spoof-location/': typeof FrSpoofLocationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/engine-level-spoofing': typeof EngineLevelSpoofingRoute
  '/privacy': typeof PrivacyRoute
  '/spoof-timezone': typeof SpoofTimezoneRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/vpn': typeof VpnRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/engine-level-spoofing': typeof FrEngineLevelSpoofingRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/spoof-timezone': typeof FrSpoofTimezoneRoute
  '/fr/support': typeof FrSupportRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr/verify': typeof FrVerifyRoute
  '/fr/vpn': typeof FrVpnRoute
  '/spoof-location/chrome': typeof SpoofLocationChromeRoute
  '/spoof-location/edge': typeof SpoofLocationEdgeRoute
  '/spoof-location/firefox': typeof SpoofLocationFirefoxRoute
  '/spoof-location/safari': typeof SpoofLocationSafariRoute
  '/blog': typeof BlogIndexRoute
  '/fr': typeof FrIndexRoute
  '/spoof-location': typeof SpoofLocationIndexRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/fr/spoof-location/chrome': typeof FrSpoofLocationChromeRoute
  '/fr/spoof-location/edge': typeof FrSpoofLocationEdgeRoute
  '/fr/spoof-location/firefox': typeof FrSpoofLocationFirefoxRoute
  '/fr/spoof-location/safari': typeof FrSpoofLocationSafariRoute
  '/fr/blog': typeof FrBlogIndexRoute
  '/fr/spoof-location': typeof FrSpoofLocationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/engine-level-spoofing': typeof EngineLevelSpoofingRoute
  '/fr': typeof FrRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/spoof-timezone': typeof SpoofTimezoneRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/vpn': typeof VpnRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/engine-level-spoofing': typeof FrEngineLevelSpoofingRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/spoof-timezone': typeof FrSpoofTimezoneRoute
  '/fr/support': typeof FrSupportRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr/verify': typeof FrVerifyRoute
  '/fr/vpn': typeof FrVpnRoute
  '/spoof-location/chrome': typeof SpoofLocationChromeRoute
  '/spoof-location/edge': typeof SpoofLocationEdgeRoute
  '/spoof-location/firefox': typeof SpoofLocationFirefoxRoute
  '/spoof-location/safari': typeof SpoofLocationSafariRoute
  '/blog/': typeof BlogIndexRoute
  '/fr/': typeof FrIndexRoute
  '/spoof-location/': typeof SpoofLocationIndexRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/fr/spoof-location/chrome': typeof FrSpoofLocationChromeRoute
  '/fr/spoof-location/edge': typeof FrSpoofLocationEdgeRoute
  '/fr/spoof-location/firefox': typeof FrSpoofLocationFirefoxRoute
  '/fr/spoof-location/safari': typeof FrSpoofLocationSafariRoute
  '/fr/blog/': typeof FrBlogIndexRoute
  '/fr/spoof-location/': typeof FrSpoofLocationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/engine-level-spoofing'
    | '/fr'
    | '/privacy'
    | '/spoof-timezone'
    | '/support'
    | '/terms'
    | '/test'
    | '/verify'
    | '/vpn'
    | '/blog/$slug'
    | '/fr/about'
    | '/fr/engine-level-spoofing'
    | '/fr/privacy'
    | '/fr/spoof-timezone'
    | '/fr/support'
    | '/fr/terms'
    | '/fr/verify'
    | '/fr/vpn'
    | '/spoof-location/chrome'
    | '/spoof-location/edge'
    | '/spoof-location/firefox'
    | '/spoof-location/safari'
    | '/blog/'
    | '/fr/'
    | '/spoof-location/'
    | '/fr/blog/$slug'
    | '/fr/spoof-location/chrome'
    | '/fr/spoof-location/edge'
    | '/fr/spoof-location/firefox'
    | '/fr/spoof-location/safari'
    | '/fr/blog/'
    | '/fr/spoof-location/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/engine-level-spoofing'
    | '/privacy'
    | '/spoof-timezone'
    | '/support'
    | '/terms'
    | '/test'
    | '/verify'
    | '/vpn'
    | '/blog/$slug'
    | '/fr/about'
    | '/fr/engine-level-spoofing'
    | '/fr/privacy'
    | '/fr/spoof-timezone'
    | '/fr/support'
    | '/fr/terms'
    | '/fr/verify'
    | '/fr/vpn'
    | '/spoof-location/chrome'
    | '/spoof-location/edge'
    | '/spoof-location/firefox'
    | '/spoof-location/safari'
    | '/blog'
    | '/fr'
    | '/spoof-location'
    | '/fr/blog/$slug'
    | '/fr/spoof-location/chrome'
    | '/fr/spoof-location/edge'
    | '/fr/spoof-location/firefox'
    | '/fr/spoof-location/safari'
    | '/fr/blog'
    | '/fr/spoof-location'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/engine-level-spoofing'
    | '/fr'
    | '/privacy'
    | '/spoof-timezone'
    | '/support'
    | '/terms'
    | '/test'
    | '/verify'
    | '/vpn'
    | '/blog/$slug'
    | '/fr/about'
    | '/fr/engine-level-spoofing'
    | '/fr/privacy'
    | '/fr/spoof-timezone'
    | '/fr/support'
    | '/fr/terms'
    | '/fr/verify'
    | '/fr/vpn'
    | '/spoof-location/chrome'
    | '/spoof-location/edge'
    | '/spoof-location/firefox'
    | '/spoof-location/safari'
    | '/blog/'
    | '/fr/'
    | '/spoof-location/'
    | '/fr/blog/$slug'
    | '/fr/spoof-location/chrome'
    | '/fr/spoof-location/edge'
    | '/fr/spoof-location/firefox'
    | '/fr/spoof-location/safari'
    | '/fr/blog/'
    | '/fr/spoof-location/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EngineLevelSpoofingRoute: typeof EngineLevelSpoofingRoute
  FrRoute: typeof FrRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SpoofTimezoneRoute: typeof SpoofTimezoneRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TestRoute: typeof TestRoute
  VerifyRoute: typeof VerifyRoute
  VpnRoute: typeof VpnRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SpoofLocationChromeRoute: typeof SpoofLocationChromeRoute
  SpoofLocationEdgeRoute: typeof SpoofLocationEdgeRoute
  SpoofLocationFirefoxRoute: typeof SpoofLocationFirefoxRoute
  SpoofLocationSafariRoute: typeof SpoofLocationSafariRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SpoofLocationIndexRoute: typeof SpoofLocationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vpn': {
      id: '/vpn'
      path: '/vpn'
      fullPath: '/vpn'
      preLoaderRoute: typeof VpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-timezone': {
      id: '/spoof-timezone'
      path: '/spoof-timezone'
      fullPath: '/spoof-timezone'
      preLoaderRoute: typeof SpoofTimezoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine-level-spoofing': {
      id: '/engine-level-spoofing'
      path: '/engine-level-spoofing'
      fullPath: '/engine-level-spoofing'
      preLoaderRoute: typeof EngineLevelSpoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-location/': {
      id: '/spoof-location/'
      path: '/spoof-location'
      fullPath: '/spoof-location/'
      preLoaderRoute: typeof SpoofLocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof FrRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-location/safari': {
      id: '/spoof-location/safari'
      path: '/spoof-location/safari'
      fullPath: '/spoof-location/safari'
      preLoaderRoute: typeof SpoofLocationSafariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-location/firefox': {
      id: '/spoof-location/firefox'
      path: '/spoof-location/firefox'
      fullPath: '/spoof-location/firefox'
      preLoaderRoute: typeof SpoofLocationFirefoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-location/edge': {
      id: '/spoof-location/edge'
      path: '/spoof-location/edge'
      fullPath: '/spoof-location/edge'
      preLoaderRoute: typeof SpoofLocationEdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoof-location/chrome': {
      id: '/spoof-location/chrome'
      path: '/spoof-location/chrome'
      fullPath: '/spoof-location/chrome'
      preLoaderRoute: typeof SpoofLocationChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/vpn': {
      id: '/fr/vpn'
      path: '/vpn'
      fullPath: '/fr/vpn'
      preLoaderRoute: typeof FrVpnRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/verify': {
      id: '/fr/verify'
      path: '/verify'
      fullPath: '/fr/verify'
      preLoaderRoute: typeof FrVerifyRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/terms': {
      id: '/fr/terms'
      path: '/terms'
      fullPath: '/fr/terms'
      preLoaderRoute: typeof FrTermsRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/support': {
      id: '/fr/support'
      path: '/support'
      fullPath: '/fr/support'
      preLoaderRoute: typeof FrSupportRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/spoof-timezone': {
      id: '/fr/spoof-timezone'
      path: '/spoof-timezone'
      fullPath: '/fr/spoof-timezone'
      preLoaderRoute: typeof FrSpoofTimezoneRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/privacy': {
      id: '/fr/privacy'
      path: '/privacy'
      fullPath: '/fr/privacy'
      preLoaderRoute: typeof FrPrivacyRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/engine-level-spoofing': {
      id: '/fr/engine-level-spoofing'
      path: '/engine-level-spoofing'
      fullPath: '/fr/engine-level-spoofing'
      preLoaderRoute: typeof FrEngineLevelSpoofingRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/about': {
      id: '/fr/about'
      path: '/about'
      fullPath: '/fr/about'
      preLoaderRoute: typeof FrAboutRouteImport
      parentRoute: typeof FrRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/spoof-location/': {
      id: '/fr/spoof-location/'
      path: '/spoof-location'
      fullPath: '/fr/spoof-location/'
      preLoaderRoute: typeof FrSpoofLocationIndexRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/blog/': {
      id: '/fr/blog/'
      path: '/blog'
      fullPath: '/fr/blog/'
      preLoaderRoute: typeof FrBlogIndexRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/spoof-location/safari': {
      id: '/fr/spoof-location/safari'
      path: '/spoof-location/safari'
      fullPath: '/fr/spoof-location/safari'
      preLoaderRoute: typeof FrSpoofLocationSafariRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/spoof-location/firefox': {
      id: '/fr/spoof-location/firefox'
      path: '/spoof-location/firefox'
      fullPath: '/fr/spoof-location/firefox'
      preLoaderRoute: typeof FrSpoofLocationFirefoxRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/spoof-location/edge': {
      id: '/fr/spoof-location/edge'
      path: '/spoof-location/edge'
      fullPath: '/fr/spoof-location/edge'
      preLoaderRoute: typeof FrSpoofLocationEdgeRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/spoof-location/chrome': {
      id: '/fr/spoof-location/chrome'
      path: '/spoof-location/chrome'
      fullPath: '/fr/spoof-location/chrome'
      preLoaderRoute: typeof FrSpoofLocationChromeRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/blog/$slug': {
      id: '/fr/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/fr/blog/$slug'
      preLoaderRoute: typeof FrBlogSlugRouteImport
      parentRoute: typeof FrRoute
    }
  }
}

interface FrRouteChildren {
  FrAboutRoute: typeof FrAboutRoute
  FrEngineLevelSpoofingRoute: typeof FrEngineLevelSpoofingRoute
  FrPrivacyRoute: typeof FrPrivacyRoute
  FrSpoofTimezoneRoute: typeof FrSpoofTimezoneRoute
  FrSupportRoute: typeof FrSupportRoute
  FrTermsRoute: typeof FrTermsRoute
  FrVerifyRoute: typeof FrVerifyRoute
  FrVpnRoute: typeof FrVpnRoute
  FrIndexRoute: typeof FrIndexRoute
  FrBlogSlugRoute: typeof FrBlogSlugRoute
  FrSpoofLocationChromeRoute: typeof FrSpoofLocationChromeRoute
  FrSpoofLocationEdgeRoute: typeof FrSpoofLocationEdgeRoute
  FrSpoofLocationFirefoxRoute: typeof FrSpoofLocationFirefoxRoute
  FrSpoofLocationSafariRoute: typeof FrSpoofLocationSafariRoute
  FrBlogIndexRoute: typeof FrBlogIndexRoute
  FrSpoofLocationIndexRoute: typeof FrSpoofLocationIndexRoute
}

const FrRouteChildren: FrRouteChildren = {
  FrAboutRoute: FrAboutRoute,
  FrEngineLevelSpoofingRoute: FrEngineLevelSpoofingRoute,
  FrPrivacyRoute: FrPrivacyRoute,
  FrSpoofTimezoneRoute: FrSpoofTimezoneRoute,
  FrSupportRoute: FrSupportRoute,
  FrTermsRoute: FrTermsRoute,
  FrVerifyRoute: FrVerifyRoute,
  FrVpnRoute: FrVpnRoute,
  FrIndexRoute: FrIndexRoute,
  FrBlogSlugRoute: FrBlogSlugRoute,
  FrSpoofLocationChromeRoute: FrSpoofLocationChromeRoute,
  FrSpoofLocationEdgeRoute: FrSpoofLocationEdgeRoute,
  FrSpoofLocationFirefoxRoute: FrSpoofLocationFirefoxRoute,
  FrSpoofLocationSafariRoute: FrSpoofLocationSafariRoute,
  FrBlogIndexRoute: FrBlogIndexRoute,
  FrSpoofLocationIndexRoute: FrSpoofLocationIndexRoute,
}

const FrRouteWithChildren = FrRoute._addFileChildren(FrRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EngineLevelSpoofingRoute: EngineLevelSpoofingRoute,
  FrRoute: FrRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SpoofTimezoneRoute: SpoofTimezoneRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TestRoute: TestRoute,
  VerifyRoute: VerifyRoute,
  VpnRoute: VpnRoute,
  BlogSlugRoute: BlogSlugRoute,
  SpoofLocationChromeRoute: SpoofLocationChromeRoute,
  SpoofLocationEdgeRoute: SpoofLocationEdgeRoute,
  SpoofLocationFirefoxRoute: SpoofLocationFirefoxRoute,
  SpoofLocationSafariRoute: SpoofLocationSafariRoute,
  BlogIndexRoute: BlogIndexRoute,
  SpoofLocationIndexRoute: SpoofLocationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
